prod_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('product.urls', namespace='product'))
]

product/urls.py
from django.conf.urls import url
from product.views import Products, ProductItem


urlpatterns = [
    url(r'^products/$', Products.as_view(), name='index'),
    url(r'^products/(?P<slug>[-\w]+)$', ProductItem.as_view(), name='product_item')
]

comment/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone

from product.models import Product


class Comment(models.Model):
    message = models.TextField(_('Message'))
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        _('Created time'),
        default=timezone.now,
        blank=True,
        null=True
    )
    modified_at = models.DateTimeField(_('Modified time'), auto_now=True)

    def __str__(self):
        return 'comment for product "{0}" was added at {1}'.format(
            self.product.name,
            self.created_at
        )

    class Meta:
        ordering = ['-created_at', ]

like/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from product.models import Product


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return 'use {username} likes "{product_name}"'.format(
            username=self.user.username,
            product_name=self.product.name
        )

    class Meta():
        unique_together = (('user', 'product'),)

product/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import gettext as _


class Product(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    slug = models.SlugField(_('Slug'), max_length=100)
    description = models.TextField(_('Description'), null=True, blank=True)
    price = models.DecimalField(_('Price'), decimal_places=2, max_digits=10)
    created_at = models.DateTimeField(_('Created time'), auto_now_add=True)
    modified_at = models.DateTimeField(_('Modified time'), auto_now=True)

    def get_absolute_url(self):
        return reverse('product:product_item', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

comment/forms.py
from __future__ import unicode_literals
from django import forms
from django.utils.translation import gettext as _

from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message', 'product']
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control'}),
            'product': forms.HiddenInput()
        }
        error_messages = {
            'message': {
                'required': _("Message can not be empty"),
            },
        }

like/forms.py
from django import forms
from like.models import Like


class LikeForm(forms.ModelForm):
    class Meta:
        model = Like
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
            'product': forms.HiddenInput()
        }

like/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import View, ListView, DetailView, TemplateView
from django.utils.translation import gettext as _
from django.utils import timezone
from django.db.models import Count

from product.models import Product
from comment.models import Comment
from like.models import Like
from comment.forms import CommentForm
from like.forms import LikeForm

from datetime import timedelta
from collections import namedtuple

""" Form handler to be user with other forms in one view

    attribures:
    name: form name
    form: form object
    template_form: initiated form object
    auth_pass: can be user to disable form processing
    success_msg: message ufter form submission
"""
ViewForm = namedtuple('ViewForm', (
    'name',
    'form',
    'auth_pass',
    'success_msg'
))


class Products(ListView):
    template_name = 'product/products.html'
    model = Product
    paginate_by = 10

    def get_queryset(self):
        """Add ordering elements by likes"""

        queryset = self.model.objects.annotate(likes=Count('like'))
        if self.request.GET.get('likes') == 'desc':
            queryset = queryset.order_by('-likes')
        elif self.request.GET.get('likes') == 'asc':
            queryset = queryset.order_by('likes')

        return queryset


class ProductItem(DetailView):
    template_name = 'product/product_item.html'
    model = Product

    def get_context_data(self, **kwargs):
        """Populate context

        Add CommentForm, LikeForm, comments, like counter, can_like to  the context
        """

        self.object = self.get_object()
        context = super(ProductItem, self).get_context_data(**kwargs)

        self.forms = {
            'form_comment': ViewForm(
                name='form_comment',
                form=CommentForm,
                auth_pass=True,
                success_msg=_('Comment was successfully added')
            ),
            'form_like': ViewForm(
                name='form_like',
                form=LikeForm,
                auth_pass=self.request.user.is_authenticated(),
                success_msg=_("You've liked this product")
            )
        }
        context['form_comment'] = self.forms['form_comment'].form(initial={'product': self.object.id})
        context['form_like'] = self.forms['form_like'].form(initial={
            'user': self.request.user.id, 'product': self.object.id}
        )

        context['comments'] = Comment.objects.filter(
            product=self.object, created_at__gte=timezone.now()-timedelta(days=1)
        )

        context['likes_count'] = Like.objects.filter(product=self.object).count()

        context['can_like'] = (
            self.request.user.is_authenticated() and
            not Like.objects.filter(product=self.object, user=self.request.user)
        )

        return context

    def post(self, request, slug):
        """Handle Like and Comment forms"""

        context = self.get_context_data()

        # go through forms and handle one in post was from it
        for viewForm in self.forms.values():
            if viewForm.name not in request.POST or not viewForm.auth_pass:
                continue
            context[viewForm.name] = viewForm.form(request.POST)
            if context[viewForm.name].is_valid():
                context[viewForm.name].save()
                messages.info(request, viewForm.success_msg)
                return redirect('product:product_item', slug=self.object.slug)
            return render(request, self.template_name, context)

        return self.http_method_not_allowed(request)

product/templates/product/product_item.html
{% extends "base.html" %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'product:index' %}">Products</a></li>
        <li class="active">{{object.name}}</li>
    </ol>
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="jumbotron">
                <h1>{{ object.name }}</h1>
                <p class="text-justify">{{ object.description }}</p>
                <form class="" method="post">
                    {% csrf_token %}
                    {{form_like}}
                    <button
                        class="pull-right btn {% if can_like %}btn-primary{% else %}btn-success{% endif %}"
                        type="submit"
                        name="form_like"
                        {% if not can_like %}disabled{% endif %}
                    >
                        Likes <span class="badge">{{likes_count}}</span>
                    </button>
                </form>
            </div>
        </div>
    </section>
    <section>
        <div class="container" id="form_comment">
            <div class="panel panel-default">
                <div class="panel-heading">Comment product</div>
                <div class="panel-body">
                    {{form_comment.errors}}
                    <form class="" action="#form_comment" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {% include "messages.html" with messages=form_comment.message.errors status="danger"%}
                            {{form_comment.product}}
                            {{form_comment.message}}
                        </div>
                        <input  class="btn btn-default push-right" type="submit" name="form_comment"/>
                    </form>
                </div>
            </div>
            <div class="comments">
                {% for comment in comments %}
                <div class="panel panel-default">
                    <div class="panel-heading">{{comment.created_at}}</div>
                    <div class="panel-body">{{comment.message}}</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

product/templates/product/products.html
{% extends "base.html" %}

{% block content %}
    <section>
        <div class="container">
            <h1>Products</h1>
            <table class="table">
                <thead>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>
                        <a href="?{% if request.GET.likes == 'desc' %}likes=asc{% else %}likes=desc{% endif %}{% if request.GET.page %}&page={{request.GET.page}}{% endif %}">Likes</a>
                    </th>
                </thead>
                <tbody>
                    {% for product in object_list %}
                    <tr>
                        <td><a href="{% url 'product:product_item' slug=product.slug %}">{{product.name}}</a></td>
                        <td>{{product.description}}</td>
                        <td>{{product.price}}</td>
                        <td>{{product.likes}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
    <section>
        <div class="container">
            <ul class="pager">
                {% if page_obj.has_previous %}
                <li><a href="?page={{page_obj.previous_page_number}}{% if request.GET.likes %}&likes={{request.GET.likes }}{% endif %}">Previous</a></li>
                {% else %}
                <li class="disabled"><a>Previous</a></li>
                {% endif %}
                <li>{{page_obj.number}} of {{page_obj.end_index}}</li>
                {% if page_obj.has_next %}
                <li><a href="?page={{page_obj.next_page_number}}{% if request.GET.likes %}&likes={{request.GET.likes }}{% endif %}">Next</a></li>
                {% else %}
                <li class="disabled"><a href="#">Previous</a></li>
                {% endif %}
            </ul>
        </div>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Product!</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class=""><a href="#">Login</a></li>
                </ul>
            </div>
        </nav>
        <section>
            <div class="container">
                {% block breadcrumbs %}{% endblock %}
            </div>
        </section>

        {% block messages %}
        <section>
            <div class="container">
                {% include "messages.html" %}
            </div>
        </section>
        {% endblock %}

        {% block content %} {% endblock %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-{{status|default:'success'}} alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <strong>{{ message }}</strong>
    </div>
    {% endfor %}
</ul>
{% endif %}